{
    {r"<ref>": r"\footnote{"},
    {r"</ref>": r"}"},
    {r"\n====": r"\subsubsection{"},
    {r"==== ": r"}"},
    {r"\n===": r"\subsection{"},
    {r"=== ": r"}"},
    {r"\n==": "\section{"},
    {r"== ": r"}"},
    {r" '''": r"\textbf{"},
    {r"''' ": r"}"},
    {r"''": "\\textit{"},
    {r"'' ": r"}"},
    {r"\n *": r"\n\item "},
    {r"[[": "\href{"},
    {r"]]": "}"},
    {r"[": "\href{"},
    {r"]": "}"},
    {r"{{": ""},
    {r"}}": ""},
    {r"|": "}{"},
    {r"<math>": r"\begin{equation}"},
    {r"</math>": r"\end{equation}"},
    {r"<code>": r"\begin{verbatim}"},
    {r"</code>": r"\end{verbatim}"},
    {r"[http": r"\href{http"},
    {r"]": "}"},
}
